import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/layout/header";
import SwitchNav from "@/components/features/switchNav";
import Providers from '@/components/providers/Providers';
import LoadingScreen from '@/components/features/LoadingScreen';
import Footer from "@/components/layout/footer";

import "./globals.css";
import "@/styles/harmony.scss";
import '@/components/features/feature.scss'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LoadingScreen />
        <Header />
        <Providers>
          <main>
            <SwitchNav />
            {children}
          </main>
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
