import React, { Suspense } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/layout/header";
import Providers from '@/components/layout/Providers';
import LoadingScreen from '@/components/features/LoadingScreen';
import ResponsiveNavWidthProvider from '@/hooks/ResponsiveNavWidthProvider';

// 懒加载组件
const SwitchNav = React.lazy(() => import("@/components/features/switchNav"));
const Footer = React.lazy(() => import("@/components/layout/footer"));

import "./globals.css";
import "@/styles/harmony.scss";
import '@/components/features/feature.scss'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <LoadingScreen />
          <ResponsiveNavWidthProvider />
          <Header />
          <main>
            <Suspense fallback={<div className="loading-placeholder">加载导航中...</div>}>
              <SwitchNav />
            </Suspense>
            <div className={`mainPage`}>
              <div className="bg-filter"></div>  
              {children}
            </div>
            <Suspense fallback={<div className="loading-placeholder">加载页脚中...</div>}>
              <Footer />
            </Suspense>
          </main>
        </Providers>
      </body>
    </html>
  );
}